add() : update in makefile, updated readme, update verification logic adjusted

diff --git a/packages/smart-contracts/Makefile.example b/packages/smart-contracts/Makefile.example
--- a/packages/smart-contracts/Makefile.example
+++ b/packages/smart-contracts/Makefile.example
@@ -3,29 +3,29 @@
 # RPC URL
 RPC_URL := 127.0.0.1:8545
 
-# Private keys
-PK_0 := 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80	# ID 0 in anvil
-PK_1 := 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d 	# ID 1 in anvil
-PK_2 := 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a  # ID 2 in anvil
-PK_3 := 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6  # ID 3 in anvil
-PK_4 := 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a  # ID 4 in anvil
-PK_5 := 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba  # ID 5 in anvil
-PK_6 := 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e  # ID 6 in anvil
-PK_7 := 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356  # ID 7 in anvil
-PK_8 := 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97  # ID 8 in anvil
-PK_9 := 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6  # ID 9 in anvil
+# Private keys  |  keep comments close cause otherwise parser breaks.
+PK_0 := 0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80# ID 0 in anvil
+PK_1 := 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d# ID 1 in anvil
+PK_2 := 0x5de4111afa1a4b94908f83103eb1f1706367c2e68ca870fc3fb9a804cdab365a# ID 2 in anvil
+PK_3 := 0x7c852118294e51e653712a81e05800f419141751be58f605c371e15141b007a6# ID 3 in anvil
+PK_4 := 0x47e179ec197488593b187f80a00eb0da91f1b9d0b13f8733639f19c30a34926a# ID 4 in anvil
+PK_5 := 0x8b3a350cf5c34c9194ca85829a2df0ec3153be0318b5e2d3348e872092edffba# ID 5 in anvil
+PK_6 := 0x92db14e403b83dfe3df233f83dfa3a0d7096f21ca9b0d6d6b8d88b2b4ec1564e# ID 6 in anvil
+PK_7 := 0x4bbbf85ce3377467afe5d46f804f221813b2bb87f24d81f60f1fcdbf7cbf4356# ID 7 in anvil
+PK_8 := 0xdbda1821b80551c9d65939329250298aa3472ba22feea921c0cf5d620ea67b97# ID 8 in anvil
+PK_9 := 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6# ID 9 in anvil
 
-# Wallet addresses
-ADDR_0 := 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266 # addr 0 in anvil
-ADDR_1 := 0x70997970C51812dc3A010C7d01b50e0d17dc79C8 # addr 1 in anvil
-ADDR_2 := 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC # addr 2 in anvil
-ADDR_3 := 0x90F79bf6EB2c4f870365E785982E1f101E93b906 # addr 3 in anvil
-ADDR_4 := 0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65 # addr 4 in anvil
-ADDR_5 := 0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc # addr 5 in anvil
-ADDR_6 := 0x976EA74026E726554dB657fA54763abd0C3a0aa9 # addr 6 in anvil
-ADDR_7 := 0x14dC79964da2C08b23698B3D3cc7Ca32193d9955 # addr 7 in anvil
-ADDR_8 := 0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f # addr 8 in anvil
-ADDR_9 := 0xa0Ee7A142d267C1f36714E4a8F75612F20a79720 # addr 9 in anvil
+# Wallet addresses  |  keep comments close cause otherwise parser breaks.
+ADDR_0 := 0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266# addr 0 in anvil
+ADDR_1 := 0x70997970C51812dc3A010C7d01b50e0d17dc79C8# addr 1 in anvil
+ADDR_2 := 0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC# addr 2 in anvil
+ADDR_3 := 0x90F79bf6EB2c4f870365E785982E1f101E93b906# addr 3 in anvil
+ADDR_4 := 0x15d34AAf54267DB7D7c367839AAf71A00a2C6A65# addr 4 in anvil
+ADDR_5 := 0x9965507D1a55bcC2695C58ba16FB37d819B0A4dc# addr 5 in anvil
+ADDR_6 := 0x976EA74026E726554dB657fA54763abd0C3a0aa9# addr 6 in anvil
+ADDR_7 := 0x14dC79964da2C08b23698B3D3cc7Ca32193d9955# addr 7 in anvil
+ADDR_8 := 0x23618e81E3f5cdF7f54C3d65f7FBc0aBf5B21E8f# addr 8 in anvil
+ADDR_9 := 0xa0Ee7A142d267C1f36714E4a8F75612F20a79720# addr 9 in anvil
 
 # -----------------------
 # Helper: pick USER key
@@ -244,7 +244,7 @@ call-switchAssets:
 call-create-new-will:
 	@echo "Creating new will at $(WILL_ADDR) by user $(USER_KEY)."
 	@cast send $(WILL_ADDR) "createNewWill((address,uint8)[],(uint256,uint256))" \
-	"[(0x70997970C51812dc3A010C7d01b50e0d17dc79C8,1),(0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC,2)]" \
+	"[($(ADDR_1),1),($(ADDR_2),2)]" \
 	"(60,120)" \
 	--private-key $(USER_PK) --rpc-url $(RPC_URL); \
 	if [ $$? -eq 0 ]; then \
@@ -252,3 +252,64 @@ call-create-new-will:
 	else \
 		echo "Status: Failed"; \
 	fi
+
+call-update-sm-upd:
+	@echo "Updating will at $(WILL_ADDR) by user $(USER_KEY)."
+	@echo "The target of the update is : Existent SM list."
+	@cast send $(WILL_ADDR) "updateWill((address,uint8)[],(address,uint8)[],address[],(uint256,uint256))" \
+	"[($(ADDR_1),3),($(ADDR_2),3)]" \
+	"[]" \
+	"[]" \
+	"(0,0)" \
+	--private-key $(USER_PK) --rpc-url $(RPC_URL); \
+	if [ $$? -eq 0 ]; then \
+		echo "Status: Success"; \
+	else \
+		echo "Status: Failed"; \
+	fi
+
+call-update-sm-add:
+	@echo "Updating will at $(WILL_ADDR) by user $(USER_KEY)."
+	@echo "The target of the update is : New SM added."
+	@cast send $(WILL_ADDR) "updateWill((address,uint8)[],(address,uint8)[],address[],(uint256,uint256))" \
+	"[]" \
+	"[($(ADDR_1),3)]" \
+	"[]" \
+	"(0,0)" \
+	--private-key $(USER_PK) --rpc-url $(RPC_URL); \
+	if [ $$? -eq 0 ]; then \
+		echo "Status: Success"; \
+	else \
+		echo "Status: Failed"; \
+	fi
+
+call-update-sm-del:
+	@echo "Updating will at $(WILL_ADDR) by user $(USER_KEY)."
+	@echo "The target of the update is : Deleting existing SM."
+	@cast send $(WILL_ADDR) "updateWill((address,uint8)[],(address,uint8)[],address[],(uint256,uint256))" \
+	"[]" \
+	"[]" \
+	"[$(ADDR_0)]" \
+	"(0,0)" \
+	--private-key $(USER_PK) --rpc-url $(RPC_URL); \
+	if [ $$? -eq 0 ]; then \
+		echo "Status: Success"; \
+	else \
+		echo "Status: Failed"; \
+	fi
+
+call-update-sec-upd:
+	@echo "Updating will at $(WILL_ADDR) by user $(USER_KEY)."
+	@echo "The target of the update is : SecurityPeriodConfig"
+	@cast send $(WILL_ADDR) "updateWill((address,uint8)[],(address,uint8)[],address[],(uint256,uint256))" \
+	"[]" \
+	"[]" \
+	"[]" \
+	"(50,50)" \
+	--private-key $(USER_PK) --rpc-url $(RPC_URL); \
+	if [ $$? -eq 0 ]; then \
+		echo "Status: Success"; \
+	else \
+		echo "Status: Failed"; \
+	fi
+
